### ISSUE TITLE
Definir o Jogo

### ISSUE THREAD

**Issue by Francinerd** [FT-riddle/jogo-web#2]
- [x] Referências: literatura, mídias em geral e outros jogos.
- [x] Roteiro: início. meio e fim.
- [x] Personagens: perfis, evolução.
- [x] Artefatos: códigos
- [x] Mundo/Universo

**Comment by Francinerd** [comment]
Refererência literária e cinematográfica
- "O código da Vinci"

**Comment by Thiago-Paim-Alflen** [comment]
Link do diário de bordo do nosso projeto contemplando todos os tópicos acima.
https://youtu.be/OYCowbIJOgY

**Comment by Francinerd** [comment]
O jogo mudou um pouco desde a primeira proposta.
