### ISSUE TITLE
Publicar a versão v0.1 do jogo no GitHub Pages

### ISSUE THREAD

**Issue by Francinerd** [FT-riddle/jogo-web#23]
Publicar o jogo em sua primeira versão experimental v0.1, no GitHub Pages para jogar nas férias de verão :)

**Comment by Francinerd** [comment]
https://ft-riddle.github.io/jogo-web/
![image](https://user-images.githubusercontent.com/74888218/110684927-7d3e4600-81bc-11eb-9655-e51fba8583ee.png)

**Comment by ghost** [comment]
A configuração do GitHub Pages está correta. Porém, o arquivo `index.html` ficou mal formatado ao copiar/colar. Recomendo pegar o arquivo do Twine e fazer _upload_ com o mesmo nome.
