### ISSUE TITLE
Estudar sobre construção de jogos

### ISSUE THREAD

**Issue by Francinerd** [FT-riddle/jogo-web#3]
- [x] https://ed.ted.com/lessons/what-makes-a-hero-matthew-winkler (vídeo do TED-ed)

 Sobre jogos digitais
- [x] https://www.youtube.com/user/McBacon1337 (canal do youtube)

**Comment by Thiago-Paim-Alflen** [comment]
Realizada a visualização dos vídeos.

**Comment by Francinerd** [comment]
Assistidos os vídeos!!
