### ISSUE TITLE
[OPCIONAL] Criar trilha sonora personalizada

### ISSUE THREAD

**Issue by Francinerd** [FT-riddle/jogo-web#39]
Trocar a música genérica de fundo em #17 por uma ou mais de sua própria autoria.

Esta tarefa é para aquele 10 não final da disciplina ...

**Comment by Francinerd** [comment]
Sugestão de ferramenta: Sonic Pi .

**Comment by Francinerd** [comment]
trilha sonora já definida

**Comment by ghost** [comment]
A trilha sonora tem arquivo já publicado, mas não localizei o arquivo de áudio personalizado.
