### ISSUE TITLE
[OPCIONAL] Criar filhos personalizado de efeito 

### ISSUE THREAD

**Issue by Francinerd** [FT-riddle/jogo-web#40]
Assim como #39 , crie filhos de efeito na substituição dos genéricos de #18 .

Esta tarefa é para aquele 10 no final da disciplina ...

**Comment by Francinerd** [comment]
Sugestão de ferramenta: ZzFXM .

**Comment by ghost** [comment]
Não localizei os arquivos de áudio personalizados.
