### ISSUE TITLE
Publicar uma versão v1.0 do jogo para computador de mesa 

### ISSUE THREAD

**Issue by Francinerd** [FT-riddle/jogo-web#41]
Publicar em redes sociais a versão v.10do jogo a ser apreciado pelo público em geral.

**Comment by Francinerd** [comment]
Funciona tanto em computador quanto celular

**Comment by ghost** [comment]
Falta marcar as tags nos commits correspondentes, conforme os [vídeos da entrega 7](https://www.youtube.com/playlist?list=PLje9mMro7hT2DE6NfFdN-icd9CYqohLuU).
