### ISSUE TITLE
Conversor de jogo para Progressive Web App (PWA) 

### ISSUE THREAD

**Issue by Francinerd** [FT-riddle/jogo-web#45]
Preparar o jogo para rodar como um PWA. Depende de #41 e #42 . Detalhe: o PWA serve tanto para computador de mesa quanto dispositivos móveis - podendo ser jogos com endereços distintos.

**Comment by ghost** [comment]
O _service worker_ não carrega no cliente - o servidor retorna 404. Tanto o arquivo `manifest.json` quando o _service worker_ não constam no código do cliente.
